name: react-native-android-build-apk
on:
  push:
    branches:
      - main
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
#      - name: Generate android folder
#        run: |
#          npx react-native init moviediscover && mv moviediscover/android android && rm -rf moviediscover && zip -r androidf.zip android
      - name: Build Android Release
        run: |
          cd android && chmod +x gradlew && ./gradlew clean && ./gradlew :app:bundleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/

